// <auto-generated />
using System;
using BuscaCnpjMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuscaCnpjMvc.Migrations
{
    [DbContext(typeof(BuscaCnpjMvcContext))]
    [Migration("20250328151557_FixedShadowPropertiesBuscaCnpj")]
    partial class FixedShadowPropertiesBuscaCnpj
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BuscaCnpjMvc.Models.CnpjResponse", b =>
                {
                    b.Property<string>("Cnpj")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Abertura")
                        .HasColumnType("longtext");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("CapitalSocial")
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("DataSituacao")
                        .HasColumnType("longtext");

                    b.Property<string>("DataSituacaoEspecial")
                        .HasColumnType("longtext");

                    b.Property<string>("Efr")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Fantasia")
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .HasColumnType("longtext");

                    b.Property<string>("MotivoSituacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Municipio")
                        .HasColumnType("longtext");

                    b.Property<string>("NaturezaJuridica")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Porte")
                        .HasColumnType("longtext");

                    b.Property<string>("Situacao")
                        .HasColumnType("longtext");

                    b.Property<string>("SituacaoEspecial")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("Uf")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Cnpj");

                    b.ToTable("CnpjResponse");
                });

            modelBuilder.Entity("BuscaCnpjMvc.Models.CnpjResponse", b =>
                {
                    b.OwnsMany("BuscaCnpjMvc.Models.AtividadePrincipal", "AtividadePrincipal", b1 =>
                        {
                            b1.Property<int>("Sequencial")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Sequencial"));

                            b1.Property<string>("Cnpj")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Code")
                                .HasColumnType("longtext");

                            b1.Property<string>("Codigo")
                                .HasColumnType("longtext");

                            b1.Property<string>("Descricao")
                                .HasColumnType("longtext");

                            b1.Property<string>("Text")
                                .HasColumnType("longtext");

                            b1.HasKey("Sequencial");

                            b1.HasIndex("Cnpj");

                            b1.ToTable("AtividadePrincipal", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("Cnpj");
                        });

                    b.OwnsMany("BuscaCnpjMvc.Models.AtividadeSecundaria", "AtividadeSecundaria", b1 =>
                        {
                            b1.Property<int>("Sequencial")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Sequencial"));

                            b1.Property<string>("Cnpj")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Code")
                                .HasColumnType("longtext");

                            b1.Property<string>("Codigo")
                                .HasColumnType("longtext");

                            b1.Property<string>("Descricao")
                                .HasColumnType("longtext");

                            b1.Property<string>("Text")
                                .HasColumnType("longtext");

                            b1.HasKey("Sequencial");

                            b1.HasIndex("Cnpj");

                            b1.ToTable("AtividadeSecundaria", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("Cnpj");
                        });

                    b.OwnsMany("BuscaCnpjMvc.Models.Qsa", "Qsa", b1 =>
                        {
                            b1.Property<int>("Sequencial")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Sequencial"));

                            b1.Property<string>("Cnpj")
                                .HasColumnType("varchar(255)");

                            b1.Property<string>("Nome")
                                .HasColumnType("longtext");

                            b1.Property<string>("NomeRepLegal")
                                .HasColumnType("longtext");

                            b1.Property<string>("PaisOrigem")
                                .HasColumnType("longtext");

                            b1.Property<string>("Qual")
                                .HasColumnType("longtext");

                            b1.Property<string>("QualRepLegal")
                                .HasColumnType("longtext");

                            b1.Property<string>("Qualificacao")
                                .HasColumnType("longtext");

                            b1.Property<string>("RepresentanteLegal")
                                .HasColumnType("longtext");

                            b1.HasKey("Sequencial");

                            b1.HasIndex("Cnpj");

                            b1.ToTable("Qsa", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("Cnpj");
                        });

                    b.OwnsOne("BuscaCnpjMvc.Models.Billing", "Billing", b1 =>
                        {
                            b1.Property<string>("CnpjResponseCnpj")
                                .HasColumnType("varchar(255)");

                            b1.Property<bool?>("Database")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("IsEmpty")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<bool?>("Optante")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("CnpjResponseCnpj");

                            b1.ToTable("CnpjResponse");

                            b1.WithOwner()
                                .HasForeignKey("CnpjResponseCnpj");
                        });

                    b.OwnsOne("BuscaCnpjMvc.Models.Simei", "Simei", b1 =>
                        {
                            b1.Property<string>("CnpjResponseCnpj")
                                .HasColumnType("varchar(255)");

                            b1.Property<DateTime?>("DataExclusao")
                                .HasColumnType("datetime(6)");

                            b1.Property<DateTime?>("DataOpcao")
                                .HasColumnType("datetime(6)");

                            b1.Property<bool>("IsEmpty")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<bool?>("Optante")
                                .HasColumnType("tinyint(1)");

                            b1.Property<DateTime?>("UltimaAtualizacao")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("CnpjResponseCnpj");

                            b1.ToTable("CnpjResponse");

                            b1.WithOwner()
                                .HasForeignKey("CnpjResponseCnpj");
                        });

                    b.OwnsOne("BuscaCnpjMvc.Models.Simples", "Simples", b1 =>
                        {
                            b1.Property<string>("CnpjResponseCnpj")
                                .HasColumnType("varchar(255)");

                            b1.Property<DateTime?>("DataExclusao")
                                .HasColumnType("datetime(6)");

                            b1.Property<DateTime?>("DataOpcao")
                                .HasColumnType("datetime(6)");

                            b1.Property<bool>("IsEmpty")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("tinyint(1)")
                                .HasDefaultValue(true);

                            b1.Property<bool?>("Optante")
                                .HasColumnType("tinyint(1)");

                            b1.Property<DateTime?>("UltimaAtualizacao")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("CnpjResponseCnpj");

                            b1.ToTable("CnpjResponse");

                            b1.WithOwner()
                                .HasForeignKey("CnpjResponseCnpj");
                        });

                    b.Navigation("AtividadePrincipal");

                    b.Navigation("AtividadeSecundaria");

                    b.Navigation("Billing");

                    b.Navigation("Qsa");

                    b.Navigation("Simei");

                    b.Navigation("Simples");
                });
#pragma warning restore 612, 618
        }
    }
}
