// <auto-generated />
using System;
using BuscaCnpjMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BuscaCnpjMvc.Migrations
{
    [DbContext(typeof(BuscaCnpjMvcContext))]
    partial class BuscaCnpjMvcContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BuscaCnpjMvc.Models.CnpjResponse", b =>
                {
                    b.Property<string>("Cnpj")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Abertura")
                        .HasColumnType("longtext");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("CapitalSocial")
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("DataSituacao")
                        .HasColumnType("longtext");

                    b.Property<string>("DataSituacaoEspecial")
                        .HasColumnType("longtext");

                    b.Property<string>("Efr")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Fantasia")
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .HasColumnType("longtext");

                    b.Property<string>("MotivoSituacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Municipio")
                        .HasColumnType("longtext");

                    b.Property<string>("NaturezaJuridica")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Porte")
                        .HasColumnType("longtext");

                    b.Property<string>("Situacao")
                        .HasColumnType("longtext");

                    b.Property<string>("SituacaoEspecial")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("Uf")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Cnpj");

                    b.ToTable("CnpjResponse", (string)null);
                });

            modelBuilder.Entity("BuscaCnpjMvc.Models.CnpjResponse", b =>
                {
                    b.OwnsMany("BuscaCnpjMvc.Models.CnpjResponse.AtividadePrincipal#BuscaCnpjMvc.Models.AtividadePrincipal", "AtividadePrincipal", b1 =>
                        {
                            b1.Property<string>("CnpjResponseCnpj")
                                .HasColumnType("varchar(255)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("CnpjResponseCnpj", "Id");

                            b1.ToTable("AtividadePrincipal", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CnpjResponseCnpj");
                        });

                    b.OwnsMany("BuscaCnpjMvc.Models.CnpjResponse.AtividadeSecundaria#BuscaCnpjMvc.Models.AtividadeSecundaria", "AtividadeSecundaria", b1 =>
                        {
                            b1.Property<string>("CnpjResponseCnpj")
                                .HasColumnType("varchar(255)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("CnpjResponseCnpj", "Id");

                            b1.ToTable("AtividadeSecundaria", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CnpjResponseCnpj");
                        });

                    b.OwnsOne("BuscaCnpjMvc.Models.CnpjResponse.Billing#BuscaCnpjMvc.Models.Billing", "Billing", b1 =>
                        {
                            b1.Property<string>("CnpjResponseCnpj")
                                .HasColumnType("varchar(255)");

                            b1.Property<bool>("Database")
                                .HasColumnType("tinyint(1)");

                            b1.Property<bool>("Optante")
                                .HasColumnType("tinyint(1)");

                            b1.HasKey("CnpjResponseCnpj");

                            b1.ToTable("CnpjResponse", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CnpjResponseCnpj");
                        });

                    b.OwnsMany("BuscaCnpjMvc.Models.CnpjResponse.Qsa#BuscaCnpjMvc.Models.Qsa", "Qsa", b1 =>
                        {
                            b1.Property<string>("CnpjResponseCnpj")
                                .HasColumnType("varchar(255)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("NomeRepLegal")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("PaisOrigem")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Qual")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("QualRepLegal")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("CnpjResponseCnpj", "Id");

                            b1.ToTable("Qsa", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CnpjResponseCnpj");
                        });

                    b.OwnsOne("BuscaCnpjMvc.Models.CnpjResponse.Simei#BuscaCnpjMvc.Models.Simei", "Simei", b1 =>
                        {
                            b1.Property<string>("CnpjResponseCnpj")
                                .HasColumnType("varchar(255)");

                            b1.Property<DateTime>("DataExclusao")
                                .HasColumnType("datetime(6)");

                            b1.Property<DateTime>("DataOpcao")
                                .HasColumnType("datetime(6)");

                            b1.Property<bool>("Optante")
                                .HasColumnType("tinyint(1)");

                            b1.Property<DateTime>("UltimaAtualizacao")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("CnpjResponseCnpj");

                            b1.ToTable("CnpjResponse", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CnpjResponseCnpj");
                        });

                    b.OwnsOne("BuscaCnpjMvc.Models.CnpjResponse.Simples#BuscaCnpjMvc.Models.Simples", "Simples", b1 =>
                        {
                            b1.Property<string>("CnpjResponseCnpj")
                                .HasColumnType("varchar(255)");

                            b1.Property<DateTime>("DataExclusao")
                                .HasColumnType("datetime(6)");

                            b1.Property<DateTime>("DataOpcao")
                                .HasColumnType("datetime(6)");

                            b1.Property<bool>("Optante")
                                .HasColumnType("tinyint(1)");

                            b1.Property<DateTime>("UltimaAtualizacao")
                                .HasColumnType("datetime(6)");

                            b1.HasKey("CnpjResponseCnpj");

                            b1.ToTable("CnpjResponse", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CnpjResponseCnpj");
                        });

                    b.Navigation("AtividadePrincipal");

                    b.Navigation("AtividadeSecundaria");

                    b.Navigation("Billing");

                    b.Navigation("Qsa");

                    b.Navigation("Simei");

                    b.Navigation("Simples");
                });
#pragma warning restore 612, 618
        }
    }
}
